POINT_DISTANCE_THRESHOLD_KM = 0.04
POINT_MAX_DISTANCE_THRESHOLD_KM = 0.5

START_RADIUS_KM = 0.02
ACTIVITY_DISTANCE_THRESHOLD_KM = 2.0

ACTIVITY_DEFAULT_PAUSE = 5
ACTIVITY_DEFAULT_DURATION_THRESHOLD = 100
